name: CI/CD on Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: self-hosted

    steps: 
    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t portfolio .

      - name: Stop existing container (if running)
        run: |
          docker stop portfolio-container || true
          docker rm portfolio-container || true
          docker container prune -f

      - name: Run Docker container
        run: |
          docker run -d -p 5000:80 --name portfolio-container portfolio
